version: '3'
services:
  db:
    image: mariadb:10-bionic
    restart: always
    networks:
      - default
    environment:
      MYSQL_USER: svs
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: svs
      MYSQL_RANDOM_ROOT_PASSWORD: yes

  go-app:
    build: .
    restart: unless-stopped
    pull_policy: build
    depends_on:
      - db
    networks:
      - proxy
      - default
    environment:
      APP_MODE: production
      CONNECTION_STRING: svs:${DB_PASSWORD}@tcp(db:3306)/svs?charset=utf8mb4&parseTime=True&loc=Local

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=https"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${ROUTER_NAME}.service=${SERVICE_NAME}"

networks:
  proxy:
    external: true
