name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      
    - name: Create data directory
      run: |
        mkdir -p data
        
    - name: Create .env file
      run: cp .env.example .env  
    
    - name: Create database (db.sqlite)
      run: go run ./seeder

    - name: Test
      run: go test ./...
